#!/bin/bash

echo "Compiling all tests..."
echo

rm ./results/tests.test

function run {
    cd bin
    ./$1 >> ../results/tests.test
    cd ..
}

if [ -z $1 ]; then

    # Run
    echo "Running tests..."
    echo ""

    for _test in $(ls -A src | grep .cpp | sed -e "s/\.cpp//g"); do
        run $_test
    done

else

    for _test in $@; do
        echo "* Running test $_test..."
        run $_test
    done
fi

echo ""
cat ./results/tests.test