#!/bin/bash

echo "Compiling all tests..."

function run {
    cd bin
    ./$1
    echo ""
    cd ..
}



if [ -z $1 ]; then

    # Run
    echo "Running tests..."
    echo ""

    for _test in $(ls -A src | grep .cpp | sed -e "s/\.cpp//g"); do
        run $_test
    done

else

    for _test in $@; do
        echo ""
        echo "* Running test $_test..."
        echo ""
        run $_test
    done
fi
