#!/bin/bash

RAKE=$(which rake)

TESTS=""
if [ $# -eq 0 ]; then
    rake
else
    for _test in $@; do
        TESTS="${TESTS} ${_test}"
    done
    unset $_test

    TESTS="${TESTS}"
    # strip
    TESTS=$(echo $TESTS | sed -e "s/^ *]?//g" -e "s/* $//g" )

    rake test["${TESTS}"]
fi
