#!/bin/bash

# define your env here
# rake will use them.
export CXX=g++
export CC=gcc

# always force to download dependencies.
sudo gem install bundler 
sudo bundler install
# export DIFF_IMAGE=diffimg

ruby ./api/tester.rb $@
