#!/bin/bash

# define your env here
# rake will use them.
export CXX=g++
export CC=gcc

# export DIFF_IMAGE=diffimg

ruby ./api/tester.rb $@
tester=$(cat "./logs/exit_code.txt")
if [[ "$tester" != "0" ]] ; then
    exit 1
fi
